# --- Basic site info ---
title: HanJun Choi
lang: ko
timezone: Asia/Seoul

description: >-
  Research Interest: Image-Based Segmentation, LLM with Chemical Interaction, Drug Response Prediction

# --- Theme ---
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

# Choose one: daylight | midnight | sunrise | sunset
skin: midnight

# --- Hamilton이 기대하는 "최상위" 메타 ---
author: "HanJun Choi"             # 문자열(이름)
avatar: /assets/img/profile.png    # 아바타 이미지 경로 (루트 기준)
email: gkswns1290@gmail.com
location: Gwangju, Korea

# --- 내 페이지에서 쓸 추가 정보(선택, 자유 키) ---
role: "PhD Candidate"
org: "Aimed-lab"
github: gkswns3708
linkedin: "https://www.linkedin.com/in/한준-최-b8ab5123a"  # 전체 URL 권장

# Permalinks for posts (optional)
permalink: /:categories/:year/:month/:day/:title/
